version: "3"
services:
  frontend:
    build: ./frontend
    # image: marcelom70/interpol-frontend:latest
    ports:
      - "80:80"
  
  redis:
    image: redis:7
    ports: 
      - "6379:6379"

  backend:
    build: ./backend
    # image: marcelom70/interpol-backend:latest
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

